### ISSUE TITLE
This is amazing! Anyway to run it on a ESP32 board?

### ISSUE THREAD

**Issue by akeilox** [ecostech/viatom-ble#1]
Thank you for sharing this, great execution!

I am wondering if its possible to run this on an ESP32 board? Rasperry Pi supply restricted but there are plenty ESP32 boards out there,
like ones available from https://banggood.com/buy/esp32.html

Would appreciate if you can share Your views.

**Comment by attermann** [comment]
Hi @akeilox. You could run it on an ESP32 but not as-is. Without a linux kernel, python and bluetooth module it would be up to you to find a similarly capable bluetooth implementation on ESP32 and follow the same decoding that is taking place in this python code. It will take some work, but definitely possible.

**Comment by akeilox** [comment]
Hi @attermann 
Many thanks for your input, I have seen some ports of bLE stack and paho-mqtt for Arduino ESP32. Not sure how mature they are.
The supported Wellue devices ( O2Ring, PO3, PO4 and PO1B models) have optional Remote Monitoring dongle which I suspect runs on a ESP chip https://cdn.shopify.com/s/files/1/0248/4191/2354/products/16-1000x1000-5_480x480.jpg?v=1625457333
With one's own implementation remote monitoring and real real-time monitoring (mqtt, custom alerts) would become possible.

Will read more about it. Happy holidays!
